# Conda environment with all required packages for mLCA
name: mlca
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pandas=2.2.3
  - jinja2=3.1.6
  - pymupdf=1.26.3
  - pip
  - pip:
    - fibonacci-heap-mod==1.2
